import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  // Financial Information Styles for Contract Modal
  financialInfoContainer: {
    backgroundColor: '#F8F9FA',
    borderRadius: 8,
    padding: 12,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#E9ECEF',
  },
  financialInfoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 6,
  },
  financialInfoLabel: {
    fontSize: 14,
    color: '#495057',
    flex: 1,
  },
  financialInfoValue: {
    fontSize: 14,
    fontWeight: '600',
    color: '#212529',
    textAlign: 'right',
  },
  highlightedAmount: {
    color: '#007AFF',
    fontWeight: '700',
  },
  sufficientBalance: {
    color: '#34C759',
  },
  insufficientBalance: {
    color: '#FF3B30',
  },
  balanceWarningBox: {
    backgroundColor: '#FFF3F2',
    borderRadius: 8,
    padding: 12,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#FFCDD2',
  },
  balanceWarningRow: {
    flexDirection: 'row',
    marginBottom: 8,
  },
  warningIcon: {
    marginRight: 8,
    marginTop: 2,
  },
  insufficientBalanceText: {
    color: '#FF3B30',
    fontSize: 14,
    flex: 1,
  },
  balanceWarningTopUpButton: {
    backgroundColor: '#FF3B30',
    borderRadius: 6,
    paddingVertical: 8,
    paddingHorizontal: 12,
    alignSelf: 'flex-end',
  },
  balanceWarningTopUpButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  container: {
    flex: 1,
    backgroundColor: '#F8F9FA',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F8F9FA',
  },
  loadingText: {
    marginTop: 15,
    fontSize: 16,
    color: '#6c757d',
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F8F9FA',
    padding: 20,
  },
  errorText: {
    fontSize: 17,
    color: '#dc3545',
    textAlign: 'center',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#EEEEEE',
  },
  orderNumber: {
    fontSize: 18,
    fontWeight: '600',
    color: '#000',
    flex: 1,
  },
  statusSection: {
    backgroundColor: '#fff',
    paddingHorizontal: 16,
    paddingVertical: 12,
    marginBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#EEEEEE',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  statusPill: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    marginBottom: 6,
  },
  statusPillText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
    marginLeft: 4,
  },
  statusIcon: {
    marginRight: 4,
  },
  statusDate: {
    fontSize: 14,
    color: '#666',
    marginTop: 4,
  },
  section: {
    margin: 10,
    borderRadius: 12,
    backgroundColor: '#fff',
    // More subtle, modern shadow
    elevation: 1,
    shadowColor: 'rgba(0,0,0,0.15)',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
    borderWidth: 0.5,
    borderColor: 'rgba(0,0,0,0.05)',
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#000',
  },
  divider: {
    marginHorizontal: 16,
    backgroundColor: '#E5E5EA',
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 8,
  },
  infoIcon: {
    marginRight: 12,
    width: 24,
  },
  infoText: {
    fontSize: 16,
    color: '#333',
    flex: 1,
  },
  totalCost: {
    fontWeight: '600',
    color: '#007AFF',
  },
  // Price Highlighting styles
  pricingContainer: {
    marginTop: 12,
    backgroundColor: '#F8F9FF',
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: '#E5E9FF',
  },
  pricingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E9FF',
  },
  pricingIcon: {
    width: 24,
    alignItems: 'center',
    marginRight: 10,
  },
  pricingLabel: {
    flex: 1,
    fontSize: 15,
    color: '#555',
    fontWeight: '500',
  },
  pricingValue: {
    fontSize: 15,
    color: '#333',
    fontWeight: '600',
  },
  totalPricingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    marginTop: 5,
  },
  totalPricingLabel: {
    flex: 1,
    fontSize: 16,
    color: '#333',
    fontWeight: '600',
  },
  totalPricingValue: {
    fontSize: 18,
    color: '#34C759',
    fontWeight: 'bold',
  },
  description: {
    fontSize: 16,
    lineHeight: 24,
    color: '#333',
    paddingVertical: 8,
  },
  consultingNote: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    borderRadius: 8,
    marginVertical: 8,
  },
  noteIcon: {
    marginRight: 12,
  },
  noteText: {
    fontSize: 16,
    color: '#007AFF',
    flex: 1,
  },
  imageContainer: {
    flexDirection: 'row',
    flexWrap: 'nowrap',
    justifyContent: 'flex-start',
    paddingVertical: 12,
    paddingHorizontal: 4,
    marginBottom: 8,
  },
  image: {
    width: width * 0.38,
    height: width * 0.38,
    marginHorizontal: 6,
    borderRadius: 8,
  },
  backButton: {
    padding: 8,
    marginRight: 8,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.9)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    width: width,
    height: height,
    justifyContent: 'center',
    alignItems: 'center',
  },
  zoomedImage: {
    width: width,
    height: height * 0.8,
  },
  closeButton: {
    right: 20,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    borderRadius: 20,
    padding: 3,
  },
  appointmentLabel: {
    fontSize: 16,
    color: '#333',
    marginVertical: 8,
    marginLeft: 36,
    fontWeight: '500',
  },
  appointmentRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 5,
    paddingLeft: 10,
  },
  confirmButton: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    borderWidth: 1.5,
    borderColor: '#007AFF',
    borderRadius: 10,
    paddingVertical: 6,
    paddingHorizontal: 14,
    marginTop: 8,
    marginBottom: 8,
    backgroundColor: '#FFF9F2',
    shadowColor: '#007AFF',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
  },
  confirmButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  confirmButtonIcon: {
    marginRight: 8,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  confirmModalContent: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 20,
    width: width * 0.85,
    maxWidth: 400,
    alignItems: 'center',
  },
  confirmModalHeader: {
    alignItems: 'center',
    marginBottom: 16,
  },
  confirmModalIcon: {
    marginBottom: 12,
  },
  confirmModalTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#000',
    textAlign: 'center',
    marginBottom: 10,
  },
  confirmModalText: {
    fontSize: 15,
    color: '#333',
    marginBottom: 20,
    textAlign: 'center',
    lineHeight: 22,
  },
  confirmModalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
  },
  confirmModalButton: {
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  confirmModalButtonCancel: {
    backgroundColor: '#E5E5EA',
    flex: 1,
    marginRight: 7,
  },
  confirmModalButtonConfirm: {
    backgroundColor: '#007AFF',
    flex: 1,
    marginLeft: 7,
  },
  confirmModalButtonText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '600',
  },
  confirmModalButtonCancelText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#333',
  },
  successModalContent: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 24,
    width: width * 0.85,
    maxWidth: 400,
    alignItems: 'center',
  },
  successIcon: {
    marginBottom: 16,
  },
  successModalTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#000',
    marginBottom: 16,
    textAlign: 'center',
  },
  successModalText: {
    fontSize: 16,
    color: '#333',
    marginBottom: 24,
    textAlign: 'center',
    lineHeight: 22,
  },
  successModalButton: {
    backgroundColor: '#34C759',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  successModalButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#fff',
  },
  imageWrapper: {
    position: 'relative',
    marginRight: 10,
  },
  selectedTag: {
    position: 'absolute',
    top: 0,
    right: 0,
    zIndex: 1,
    backgroundColor: '#34C759',
    borderTopRightRadius: 8,
    borderBottomLeftRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
    flexDirection: 'row',
    alignItems: 'center',
  },
  selectedTagText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: 'bold',
  },
  selectedTagIcon: {
    marginRight: 2,
  },
  contractLoading: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  contractLoadingText: {
    marginTop: 10,
    fontSize: 14,
    color: '#666',
  },
  contractError: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  contractErrorText: {
    fontSize: 14,
    color: '#FF3B30',
    textAlign: 'center',
  },
  contractInfo: {
    paddingVertical: 10,
  },
  noContractText: {
    fontSize: 14,
    color: '#666',
    textAlign: 'center',
    padding: 20,
  },
  viewContractButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#007AFF',
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginTop: 16,
  },
  viewContractText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  viewContractIcon: {
    marginRight: 8,
  },
  signatureSection: {
    marginTop: 20,
    position: 'relative',
  },
  uploadSignatureContainer: {
    marginTop: 12,
    borderWidth: 2,
    borderColor: '#E5E5EA',
    borderStyle: 'dashed',
    borderRadius: 8,
    padding: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  uploadSignatureButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 10,
  },
  uploadIcon: {
    marginRight: 8,
  },
  uploadText: {
    fontSize: 16,
    color: '#007AFF',
    fontWeight: '500',
  },
  signatureOptionsDropdown: {
    position: 'absolute',
    top: 80,
    left: 0,
    right: 0,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    zIndex: 10,
  },
  signatureOption: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E5EA',
  },
  signatureOptionCancel: {
    justifyContent: 'center',
    backgroundColor: '#F9F9F9',
  },
  optionIcon: {
    marginRight: 16,
    width: 24,
  },
  optionText: {
    fontSize: 16,
    color: '#333',
  },
  cancelOptionText: {
    fontSize: 16,
    color: '#FF3B30',
    fontWeight: '500',
    textAlign: 'center',
  },
  signaturePreviewContainer: {
    marginTop: 12,
    borderWidth: 1,
    borderColor: '#E5E5EA',
    borderRadius: 8,
    padding: 16,
    position: 'relative',
  },
  signaturePreview: {
    width: '100%',
    height: 100,
  },
  removeSignatureButton: {
    position: 'absolute',
    top: 8,
    right: 8,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 4,
  },
  disabledButton: {
    backgroundColor: '#CCCCCC',
    opacity: 0.7,
  },
  fullScreenImage: {
    width: width * 0.95,
    height: height * 0.8,
    borderRadius: 8,
  },
  modalCloseButton: {
    position: 'absolute',
    top: 40,
    right: 20,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    borderRadius: 20,
    padding: 8,
    zIndex: 10,
  },
  guidanceHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    marginTop: 8,
    backgroundColor: '#F0F8FF',
    borderRadius: 8,
    paddingHorizontal: 12,
  },
  guidanceHeaderText: {
    fontSize: 15,
    color: '#007AFF',
    fontWeight: '500',
  },
  guidanceIcon: {
    marginRight: 8,
  },
  guidanceContent: {
    backgroundColor: '#F8F9FA',
    borderRadius: 8,
    padding: 16,
    marginTop: 8,
    borderWidth: 1,
    borderColor: '#E5E5EA',
  },
  guidanceSection: {
    marginBottom: 16,
  },
  guidanceSectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    marginBottom: 8,
  },
  guidanceText: {
    fontSize: 14,
    color: '#4A4A4A',
    marginBottom: 6,
    lineHeight: 20,
  },
  guidanceBold: {
    fontWeight: '600',
    color: '#333',
  },
  formatTag: {
    backgroundColor: '#E9ECEF',
    borderRadius: 4,
    paddingHorizontal: 6,
    paddingVertical: 2,
    marginHorizontal: 2,
    display: 'inline',
  },
  formatTagText: {
    fontSize: 12,
    color: '#495057',
  },
  buttonTag: {
    backgroundColor: '#E9ECEF',
    borderRadius: 4,
    paddingHorizontal: 6,
    paddingVertical: 2,
    display: 'inline',
  },
  buttonTagText: {
    fontSize: 12,
    color: '#495057',
    fontWeight: '500',
  },
  supportInfoContainer: {
    marginTop: 8,
    backgroundColor: '#FFF',
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: '#E5E5EA',
  },
  supportInfoRow: {
    flexDirection: 'row',
    marginBottom: 8,
    alignItems: 'center',
  },
  supportLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333',
    width: 70,
  },
  supportValue: {
    fontSize: 14,
    color: '#007AFF',
    flex: 1,
  },
  supportHours: {
    fontSize: 13,
    color: '#666',
    fontStyle: 'italic',
  },
  contractSignedContainer: {
    backgroundColor: 'rgba(52, 199, 89, 0.1)',
    borderRadius: 10,
    padding: 15,
    alignItems: 'center',
    marginBottom: 15,
    borderWidth: 1,
    borderColor: 'rgba(52, 199, 89, 0.3)',
  },
  contractSignedIcon: {
    marginBottom: 8,
  },
  contractSignedText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#34C759',
    textAlign: 'center',
  },
  
  // Payment section styles
  paymentSection: {
    padding: 10,
  },
  paymentDescription: {
    fontSize: 16,
    color: '#333',
    lineHeight: 22,
    marginBottom: 15,
  },
  paymentSummary: {
    backgroundColor: '#F8F9FA',
    borderRadius: 8,
    padding: 15,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#E5E5EA',
  },
  paymentSummaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginVertical: 6,
  },
  paymentSummaryLabel: {
    fontSize: 15,
    color: '#4A4A4A',
  },
  paymentSummaryValue: {
    fontSize: 15,
    fontWeight: '500',
    color: '#333',
  },
  totalSummaryRow: {
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#E5E5EA',
  },
  totalSummaryLabel: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
  },
  totalSummaryValue: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#007AFF',
  },
  payNowButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#34C759',
    borderRadius: 8,
    paddingVertical: 14,
    paddingHorizontal: 20,
    marginTop: 10,
  },
  payNowIcon: {
    marginRight: 10,
  },
  payNowText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  
  // Payment Modal styles
  paymentModalContent: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 0,
    width: width * 0.9,
    maxWidth: 500,
    maxHeight: height * 0.8,
  },
  paymentModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#E5E5EA',
    padding: 16,
  },
  paymentModalTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: '#000',
    marginRight: 50,
  },
  paymentDetailsContainer: {
    padding: 16,
    backgroundColor: '#F8F9FA',
  },
  paymentRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
  },
  paymentLabel: {
    fontSize: 15,
    color: '#4A4A4A',
    flex: 2,
  },
  paymentValue: {
    fontSize: 15,
    fontWeight: '500',
    color: '#333',
    flex: 1,
    textAlign: 'right',
  },
  highlightedAmount: {
    color: '#007AFF',
  },
  totalRow: {
    marginTop: 10,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#E5E5EA',
  },
  totalLabel: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
  },
  totalValue: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FF3B30',
    textAlign: 'right',
  },
  paymentInfoContainer: {
    backgroundColor: '#F1F9F1',
    borderWidth: 1,
    borderColor: '#E0F2E9',
    borderRadius: 8,
    padding: 15,
    margin: 16,
  },
  paymentButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: '#E5E5EA',
  },
  cancelButton: {
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    backgroundColor: '#F2F2F7',
    width: '40%',
    alignItems: 'center',
  },
  cancelButtonText: {
    color: '#4A4A4A',
    fontSize: 14,
    fontWeight: '500',
  },
  confirmPaymentButton: {
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    backgroundColor: '#34C759',
    width: '55%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  confirmPaymentText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  
  // Delivery tracking styles
  trackingContainer: {
    backgroundColor: '#fff',
    padding: 16,
    marginBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#EEEEEE',
  },
  trackingTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#000',
    marginBottom: 10,
  },
  deliveryCode: {
    fontSize: 14,
    color: '#666',
    marginBottom: 15,
  },
  confirmDeliveryButton: {
    backgroundColor: '#34C759',
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 20,
    marginTop: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    // Refined shadow
    elevation: 1,
    shadowColor: 'rgba(0,0,0,0.2)',
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  confirmButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  confirmButtonIcon: {
    marginRight: 10,
  },
  confirmButtonText: {
    color: '#007AFF',
    fontSize: 16,
    fontWeight: '500',
    textAlign: 'center',
  },
  
  // Redraft button styles
  redraftButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FF9500',
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginVertical: 10,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  redraftButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  redraftButtonIcon: {
    marginRight: 8,
  },
  
  // Redraft modal styles
  redraftModalContent: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 24,
    width: width * 0.85,
    maxWidth: 400,
  },
  redraftModalTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#000',
    textAlign: 'center',
    marginBottom: 16,
  },
  redraftModalText: {
    fontSize: 16,
    color: '#333',
    marginBottom: 16,
  },
  redraftReasonInput: {
    borderWidth: 1,
    borderColor: '#CCCCCC',
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    textAlignVertical: 'top',
    minHeight: 100,
    marginBottom: 20,
  },
  redraftModalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  redraftModalButton: {
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  redraftModalButtonCancel: {
    backgroundColor: '#E5E5EA',
    flex: 1,
    marginRight: 8,
  },
  redraftModalButtonConfirm: {
    backgroundColor: '#FF9500',
    flex: 2,
    marginLeft: 8,
  },
  redraftModalButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  redraftModalButtonCancelText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
  },
  
  // Material List styles
  materialItem: {
    flexDirection: 'row',
    marginVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#EEEEEE',
    paddingBottom: 12,
  },
  materialImageContainer: {
    width: 80,
    height: 80,
    borderRadius: 8,
    overflow: 'hidden',
    marginRight: 12,
  },
  materialImage: {
    width: '100%',
    height: '100%',
  },
  materialImagePlaceholder: {
    width: 80,
    height: 80,
    borderRadius: 8,
    backgroundColor: '#F0F0F0',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  materialDetails: {
    flex: 1,
    justifyContent: 'center',
  },
  materialName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#000',
    marginBottom: 6,
  },
  materialRow: {
    flexDirection: 'row',
    marginVertical: 2,
  },
  materialLabel: {
    fontSize: 14,
    color: '#666',
    marginRight: 8,
    width: 70,
  },
  materialValue: {
    fontSize: 14,
    color: '#333',
  },
  materialPriceContainer: {
    justifyContent: 'center',
    alignItems: 'flex-end',
    paddingLeft: 12,
    width: 100,
  },
  materialTotalPrice: {
    fontSize: 15,
    fontWeight: '600',
    color: '#007AFF',
  },
  materialTotalContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: 16,
    paddingTop: 12,
    borderTopColor: '#E5E5EA',
  },
  materialTotalLabel: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
    marginRight: 12,
  },
  materialTotalValue: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#007AFF',
  },
  resketchOutlinedButton: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    borderWidth: 1,
    borderColor: '#FF9500',
    borderRadius: 10,
    paddingVertical: 6,
    paddingHorizontal: 14,
    marginTop: 8,
    marginBottom: 8,
    backgroundColor: '#FFF9F2',
    // Very subtle or no shadow for outlined buttons
    shadowColor: 'transparent',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0,
    shadowRadius: 0,
  },
  resketchOutlinedButtonText: {
    color: '#FF9500',
    fontSize: 14,
    fontWeight: '600',
    marginLeft: 6,
  },
  resketchButtonIcon: {
    marginRight: 0,
  },
  modalNavButton: {
    position: 'absolute',
    top: '50%',
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    borderRadius: 40,
    width: 50,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
    marginTop: -25, // Center vertically
  },
  modalNavButtonLeft: {
    left: 20,
  },
  modalNavButtonRight: {
    right: 20,
  },
  paginationDotsContainer: {
    position: 'absolute',
    bottom: 30,
    flexDirection: 'row',
    justifyContent: 'center',
    width: '100%',
  },
  paginationDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: 'rgba(255, 255, 255, 0.5)',
    margin: 5,
  },
  paginationDotActive: {
    backgroundColor: '#FFFFFF',
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  imageCounter: {
    position: 'absolute',
    top: 40,
    left: 20,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 15,
  },
  imageCounterText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  // Cancel Service styles
  cancelServiceContainer: {
    padding: 16,
    marginVertical: 10,
    alignItems: 'center',
  },
  cancelServiceButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FF3B30',
    borderRadius: 10,
    paddingVertical: 14,
    paddingHorizontal: 24,
    width: '100%',
    // Subtle shadow
    elevation: 1,
    shadowColor: 'rgba(230, 30, 20, 0.3)',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  cancelServiceText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  cancelServiceIcon: {
    marginRight: 10,
  },
  // Financial information styles
  financialInfoContainer: {
    width: '100%',
    backgroundColor: '#F8F9FA',
    borderRadius: 8,
    padding: 12,
    marginBottom: 15,
    borderWidth: 1,
    borderColor: '#E5E5EA',
  },
  financialInfoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 6,
  },
  financialInfoLabel: {
    fontSize: 14,
    color: '#4A4A4A',
    flex: 3,
  },
  financialInfoValue: {
    fontSize: 14,
    color: '#333',
    fontWeight: '500',
    flex: 2,
    textAlign: 'right',
  },
  // Add new styles for wallet balance display
  sufficientBalance: {
    color: '#4CAF50',
    fontWeight: '600',
  },
  insufficientBalance: {
    color: '#FF3B30',
    fontWeight: '600',
  },
  balanceWarningBox: {
    backgroundColor: '#FFF0F0',
    borderRadius: 10,
    padding: 14,
    marginTop: 16,
    marginBottom: 8,
    alignItems: 'stretch',
  },
  balanceWarningRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  warningIcon: {
    marginRight: 8,
  },
  insufficientBalanceText: {
    flex: 1,
    color: '#FF3B30',
    fontSize: 15,
    fontWeight: '500',
  },
  balanceWarningTopUpButton: {
    backgroundColor: '#34C759',
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: 'center',
    marginTop: 2,
  },
  balanceWarningTopUpButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
}); 